import { Roboto } from "next/font/google";
import "./globals.css";
import TransitionProvider from "@/Components/transitionProvider"



const roboto = Roboto({ subsets: ["latin"],weight:["400","500","700"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
    <TransitionProvider>
      {children}
    </TransitionProvider>
       </body>
    </html>
  );
}

